### ISSUE TITLE
[BUG] No minimum validation for top_n_size setting

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/query-insights#11]
### What is the bug?
There is no minimum for top_n_size setting. Users can set the value to 0 or negative value which does not make sense. 

Add minimum constant here - https://github.com/opensearch-project/query-insights/blob/84e6b75fc77e463f33144b331cd402d910997f70/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java#L63

Update validator function here - https://github.com/opensearch-project/query-insights/blob/84e6b75fc77e463f33144b331cd402d910997f70/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java#L139

### How can one reproduce the bug?
```
% curl -XPUT "localhost:9200/_cluster/settings?pretty&flat_settings" -H 'Content-Type: application/json' -d '{"transient":{"search.insights.top_queries.latency.top_n_size": "-1"}}' 
{
  "acknowledged" : true,
  "persistent" : { },
  "transient" : {
    "search.insights.top_queries.latency.top_n_size" : "-1"
  }
}
```

### What is the expected behavior?
We should reject all requests which attempt to update less than some minimum value, probably 1.

**Comment by ansjcy** [comment]
[Triage]
@dzane17 Thanks for filing this issue.

**Comment by ansjcy** [comment]
This is fixed as part of https://github.com/opensearch-project/query-insights/pull/13.
