### ISSUE TITLE
[FEATURE] Top N Queries API should be able to get historical data from index

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/query-insights#12]
### Is your feature request related to a problem?
Currently we can export historical top n queries data into local index, and to view the historical data we have to manually search the index. It would be convenient if we can provide the functionality to specify time ranges in the top n queries API, and the API handles the logic to search in local index. 

### What alternatives have you considered?
We keep the current logic, but it would not be convenient for the user and also make the dashboard logic complex when getting historical top n queries.

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/reta)]
