### ISSUE TITLE
[FEATURE] Set query-insights plugin 3.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/query-insights#134]
### Is your feature request related to a problem? Please describe

Set `query-insights` plugin 3.0.0 baseline JDK version to JDK-21

### Describe the solution you'd like

See please https://github.com/opensearch-project/OpenSearch/issues/10745

### Related component

Build

### Describe alternatives you've considered

N/A

### Additional context

See please https://github.com/opensearch-project/OpenSearch/issues/14011

**Comment by msfroh** [comment]
It looks like query-insights does build + test with JDK21 on the `main` branch: https://github.com/opensearch-project/query-insights/actions/runs/11901927318/job/33165910009?pr=162

**Comment by reta** [comment]
Yes, thanks @msfroh , only misses target / source compatibility, opened  https://github.com/opensearch-project/query-insights/pull/163
