### ISSUE TITLE
[BUG] Metrics need to always be populated for query categorization to consume

### ISSUE THREAD

**Issue by deshsidd** [opensearch-project/query-insights#40]
### What is the bug?
Top N only populates metrics when the feature is enabled. Since query categorization uses all metrics irrespective of Top N enabled/disabled we need to always populate the metrics.

we need to remove the if s in this block: [https://github.com/opensearch-project/query-insights/blob/6b0ddddc034e274dd3c25813[…]search/plugin/insights/core/listener/QueryInsightsListener.java](https://github.com/opensearch-project/query-insights/blob/6b0ddddc034e274dd3c258133fe5cfddb717f5f8/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java#L157-L174)
To always populate metrics for categorization to use
[QueryInsightsListener.java](https://github.com/opensearch-project/query-insights/blob/6b0ddddc034e274dd3c258133fe5cfddb717f5f8/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java)
            if (queryInsightsService.isCollectionEnabled(MetricType.LATENCY)) {
                measurements.put(
                    MetricType.LATENCY,
                    TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - searchRequestContext.getAbsoluteStartNanos())
                );
            }
            if (queryInsightsService.isCollectionEnabled(MetricType.CPU)) {
                measurements.put(
                    MetricType.CPU,
                    tasksResourceUsages.stream().map(a -> a.getTaskResourceUsage().getCpuTimeInNanos()).mapToLong(Long::longValue).sum()
                );
            }
            if (queryInsightsService.isCollectionEnabled(MetricType.MEMORY)) {
                measurements.put(
                    MetricType.MEMORY,
                    tasksResourceUsages.stream().map(a -> a.getTaskResourceUsage().getMemoryInBytes()).mapToLong(Long::longValue).sum()
                );
            }

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by ansjcy** [comment]
Closing this since it has been fixed by https://github.com/opensearch-project/query-insights/pull/41
