### ISSUE TITLE
[BUG] Snapshots are not being published for query-insights repo

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/query-insights#72]
### What is the bug?
See the workflow runs here: https://github.com/opensearch-project/query-insights/actions/workflows/maven-publish.yml
None of them where successful before due to missing credentials. The credentials were added recently however, the required config seems to be missing for publishing snapshots.

### How can one reproduce the bug?
See https://github.com/opensearch-project/query-insights/actions/runs/10498341550/job/29083082462

### What is the expected behavior?
Snapshot publication should be successful

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishShadowPublicationToSnapshotsRepository' not found in root project 'query-insights'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./

BUILD FAILED in 28s
Error: Process completed with exit code 1.
```

**Comment by ansjcy** [comment]
Hi @gaiksaya ! Thanks for reporting the issue.
I do see query insights snapshots published in https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/query-insights/
May I know what is the main purpose of `publishShadowPublicationToSnapshotsRepository` and where should those targets come from?

**Comment by gaiksaya** [comment]
I believe it comes from nebula plugin. See this [issue](https://github.com/opensearch-project/alerting/issues/802) to add required config in build.gradle. It has testing steps as well. I believe we want `publishPluginZipPublicationToSnapshotsRepository` to run correctly. The artifacts here https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/query-insights/ were published before this plugin was removed from core right?

**Comment by ansjcy** [comment]
The latest job to publish the snapshot is passing now: https://github.com/opensearch-project/query-insights/actions/runs/10708891477/job/29692255569
