### ISSUE TITLE
[FEATURE] More integration tests for top n queries features

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/query-insights#8]
### Is your feature request related to a problem?
We have some integration tests to validate basic top N queries, but we need more tests as our features grow. We should add more integration tests for Query Insights.

### What solution would you like?
We should add more integration tests for the exporters and resource usage metrics.

**Comment by dblock** [comment]
[Catch All Triage, attendees [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/lukas-vlcek/), [4](https://github.com/rafaelma), [5](https://github.com/krisfreedain), [6](https://github.com/gargrajat), [7](https://github.com/andrross)]

**Comment by ansjcy** [comment]
Closing this with https://github.com/opensearch-project/query-insights/pull/71
