### ISSUE TITLE
[BUG] Top N API returns no results when only cpu or only memory is enabled

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/query-insights#83]
### What is the bug?
Top N API returns no results when only cpu or only memory is enabled.

In `RestTopQueriesAction` we have a single check for MetricType.LATENCY which is causing this issue:
https://github.com/opensearch-project/query-insights/blob/main/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesAction.java#L69

### How can one reproduce the bug?
1. Enable top N for cpu. Ensure latency, memory, and `search.query.metrics.enabled` are disabled.
```
curl -X PUT "localhost:9200/_cluster/settings?pretty&flat_settings" -H 'Content-Type: application/json' -d '{"transient" : {"search.insights.top_queries.cpu.enabled" : true}}'
```

2. Index data and send some search requests
```
// Bulk
curl -X POST "localhost:9200/_bulk?pretty" -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test2", "_id" : "1" } }
{ "field1" : "value1" }                          
{ "index" : { "_index" : "test2", "_id" : "2" } }
{ "field2" : "value2" }
{ "index" : { "_index" : "test2", "_id" : "3" } }
{ "field3" : "value3" }
{ "index" : { "_index" : "test2", "_id" : "4" } }
{ "field4" : "value4" }
'

// Match all
curl -X GET "http://localhost:9200/_search?pretty&phase_took" -H 'Content-Type: application/json' -d' 
{
  "query": {
    "match_all": {}
  }
}'
```

3. Get Top N
```
% curl -X GET "localhost:9200/_insights/top_queries?pretty"

{
  "top_queries" : [ ]
}
```

API will return no results even though top N cpu is enabled 

### What is the expected behavior?
Top N should return results if any 1 or more metrics (latency, cpu, memory) are enabled.

**Comment by dzane17** [comment]
If user calls Top N api without any `type` param (ex `GET /_insights/top_queries`) we use `type=latency` by default. That is why no results are returned anytime latency is disabled but cpu and/or memory are enabled.
```
final String metricType = request.param("type", MetricType.LATENCY.toString());
```

Need to update documentation:
https://opensearch.org/docs/2.16/observing-your-data/query-insights/top-n-queries/#monitoring-the-top-n-queries
```
You can use the Insights API endpoint to obtain the top N queries for all metric types:

GET /_insights/top_queries
```

**Comment by ansjcy** [comment]
@dzane17 is right, I think this is a bug introduced when adding CPU and memory as additional metric types. IMO we should not set the default metric type subjectively. But in this case we should also update the API to disallow users to call the API without the type parameter.
