### ISSUE TITLE
[FEATURE] Enrich the Operational Metrics in Query Insights

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/query-insights#9]
### Is your feature request related to a problem?
Currently, we have error logs for Query Insights, but we need to introduce more operational metrics so we can create more alarms (e.g., memory usage, queue sizes) for Query Insights features.

### What solution would you like?
Introduce additional metrics, potentially using the OpenTelemetry metric framework. The metrics should comprehensively cover:
- Size information for top queries priority queues
- Size information for multiple blocking queues
- Exported data size
- Errors and exceptions

**Comment by dblock** [comment]
[Catch All Triage, attendees [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/lukas-vlcek/), [4](https://github.com/rafaelma), [5](https://github.com/krisfreedain), [6](https://github.com/gargrajat), [7](https://github.com/andrross)]

**Comment by ansjcy** [comment]
We need to pick this up for 2.18.

**Comment by ansjcy** [comment]
We want to provide a `health_stats` API to expose the important metrics in query insights like queue sizes. Also, we need to emit metrics when error happens (possibly through oTel).
